// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/service-specification/client/config"
	"github.com/service-specification/client/dev_or_prod_mode"
	"github.com/service-specification/client/handshake"
	"github.com/service-specification/client/hello"
	"github.com/service-specification/client/session"
	"github.com/service-specification/client/session_data"
	"github.com/service-specification/client/session_refresh"
	"github.com/service-specification/client/session_user"
	"github.com/service-specification/client/session_verify"
)

// Default super tokens HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8080"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new super tokens HTTP client.
func NewHTTPClient(formats strfmt.Registry) *SuperTokens {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new super tokens HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *SuperTokens {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new super tokens client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *SuperTokens {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(SuperTokens)
	cli.Transport = transport
	cli.Config = config.New(transport, formats)
	cli.DevOrProdMode = dev_or_prod_mode.New(transport, formats)
	cli.Handshake = handshake.New(transport, formats)
	cli.Hello = hello.New(transport, formats)
	cli.Session = session.New(transport, formats)
	cli.SessionData = session_data.New(transport, formats)
	cli.SessionRefresh = session_refresh.New(transport, formats)
	cli.SessionUser = session_user.New(transport, formats)
	cli.SessionVerify = session_verify.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// SuperTokens is a client for super tokens
type SuperTokens struct {
	Config config.ClientService

	DevOrProdMode dev_or_prod_mode.ClientService

	Handshake handshake.ClientService

	Hello hello.ClientService

	Session session.ClientService

	SessionData session_data.ClientService

	SessionRefresh session_refresh.ClientService

	SessionUser session_user.ClientService

	SessionVerify session_verify.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *SuperTokens) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Config.SetTransport(transport)
	c.DevOrProdMode.SetTransport(transport)
	c.Handshake.SetTransport(transport)
	c.Hello.SetTransport(transport)
	c.Session.SetTransport(transport)
	c.SessionData.SetTransport(transport)
	c.SessionRefresh.SetTransport(transport)
	c.SessionUser.SetTransport(transport)
	c.SessionVerify.SetTransport(transport)
}
